### ISSUE TITLE
Allow option to be specifiec multiple times

### ISSUE THREAD

**Issue by vjuranek** [vjuranek/radargun-plugin#61]
Oprions like `--add-plugin` can be specified multiple times, but plugin adds it only once. Allow to specify is multiple time like cmd line.

**Comment by vjuranek** [comment]
List of options which can be specified multiple times is
* `--add-plugin`
* `--add-config`
* `--add-reporter`

**Comment by rvansa** [comment]
I would rather add multiple directly editable configurations (similar as you have file- or text-based benchmark config), so that for file-based you would have:
* plugin name
* absolute path
* (possibly) read-only box that will show you the configuration in job directly

and for text-based there'd be:
* plugin name
* configuration file name (not a path)
* textbox

**Comment by vjuranek** [comment]
@rvansa I'd say that this is actually different issue - what you propose is basically richer config for given options, but this issue deals with problem, that given option can be specified multiple times. I created #62 for what you've proposed.
